export const clients = [
  {
    full_name: "Francesca Holland",
    avatar: "https://i.pravatar.cc/150?u=a042581ssd",
    phone_number: "+1 (417) 667-8275",
    mail: "Dolore quos quod exc",
    organization: "Orr and Willis Co",
    status: "inactive",
    userId: 1,
  },
  {
    full_name: "Yasir Huber",
    avatar: "https://i.pravatar.cc/150?u=a042581ssd",
    phone_number: "+1 (555) 133-8593",
    mail: "Veritatis nobis labo",
    organization: "Barnes Washington Inc",
    status: "inactive",
    userId: 1,
  },
  {
    full_name: "Heidi Herrera",
    avatar: "https://i.pravatar.cc/150?u=a042581ssd",
    phone_number: "+1 (817) 923-6114",
    mail: "Sint recusandae Ex",
    organization: "Cline and Murphy Associates",
    status: "active",
    userId: 1,
  },
  {
    full_name: "Imogene Santos",
    avatar: "https://i.pravatar.cc/150?u=a042581ssd",
    phone_number: "+1 (931) 176-5556",
    mail: "Possimus alias sed ",
    organization: "Levine Mercado Trading",
    status: "active",
    userId: 1,
  },
  {
    full_name: "Nock Wayne",
    avatar: "https://i.pravatar.cc/150?u=a042581ssd",
    phone_number: "+9998888888",
    mail: "toot@gmail.com",
    organization: "Oorg",
    status: "active",
    userId: 1,
  },
];
