import "@app/styles/globals.css";
import { Inter } from "next/font/google";
import Navs from "../components/navbar";
import Sidebar from "../components/sidebar";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head />
      <body className={inter.className}>
        <Navs />
        <Sidebar>{children}</Sidebar>
      </body>
    </html>
  );
}
